### PR TITLE
Add filtering to CurrencyDropdownMenu

### PR DESCRIPTION
**Pull request by msaqeeb72**
Removed alert dialog from currency selection in settings and added a bottom sheet with a search feature.

WhatsApp Image 2024-10-01 at 03 19 43

### CODE REVIEW

**Comment by msaqeeb72** [comment]
I am participating in Hacktoberfest and was hoping my contribution could be counted towards my Hacktoberfest goals.

Would it be possible for you to:

1) Add the hacktoberfest topic to this repository, and
2) Tag my pull request with the hacktoberfest-accepted label?

**Comment by f33lnothin9** [comment]
Hi, currency filtering is a necessary feature, but I would like to do it with `OutlinedTextField` and `CurrencyDropdownMenu` so that I can reuse this component in other currency selection dialogs (`WalletDialog`, `SubscriptionDialog`).
{A1B1E595-73D5-40A1-A14A-EA2A5E765CB5}
https://m3.material.io/components/menus/guidelines#73531839-5ef8-46cd-9a5e-223f32912edb

**Comment by f33lnothin9** [comment]
> I am participating in Hacktoberfest and was hoping my contribution could be counted towards my Hacktoberfest goals.
> 
> Would it be possible for you to:
> 
> 1. Add the hacktoberfest topic to this repository, and
> 2. Tag my pull request with the hacktoberfest-accepted label?

Ok, I'll do it, but this feature needs to be done in a different way.

**Comment by f33lnothin9** [comment]
So, `CurrencyDialog` should look like in the picture, but instead of the usual `OutlinedTextField` you need to modify and use the existing `CurrencyDropdownMenu`.

{6F1EF306-156C-4D05-BB08-9F902FF9D398}

**Comment by msaqeeb72** [comment]
Should we use both a filtering dropdown and a bottom sheet?

On the settings page, we will show a bottom sheet for default currency selection, and in the create wallet dialog, we will show a dropdown for currency selection.

A bottom sheet is more suitable for the settings screen.

**Comment by f33lnothin9** [comment]
No, we only use the dropdown filter. We can't use the bottom sheet because it doesn't look unified with the other elements.

**Comment by msaqeeb72** [comment]
What about this?

**Comment by f33lnothin9** [comment]
That's good, did you use `ExposedDropdownMenuBox` [component](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#ExposedDropdownMenuBox(kotlin.Boolean,kotlin.Function1,androidx.compose.ui.Modifier,kotlin.Function1))? You can just modify the existing `CurrencyDropdownMenu` in `core:ui`.

**Comment by msaqeeb72** [comment]
Yes, I did same. please checkout updated commit.

**Comment by f33lnothin9** [comment]
Nice work, thank you. I'll merge it later after some fixes by me.

**Pull request merged**
